import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export const getStaticProps = async () => {
  const res = await fetch('https://edu-servers.herokuapp.com/school');
  const data = await res.json();

  return {
    props: { ninjas: data }
  }
}

const Ninjas = ({ ninjas }) => {
  console.log(ninjas)

  return (

    <>
    <Head>
        <title>Edu Hub</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>

      <h1>School</h1>
      {ninjas.map(ninja => (
        <div >
          <Link key={ninja.id} href={'/school/' + ninja.id}  >
            <h3>{ ninja.grade }</h3>
          
          </Link>
        </div>
      ))}
    </>
  );
}
 
export default Ninjas;
